### ISSUE TITLE
Gjennomgang

### ISSUE THREAD

**Issue by kimjoar** [hinderberg/backbone-structure#1]
- [x] Struktur-figur
- [x] Ekstra punkt for minnelekasjer?
- [x] Bruke subviews-eksemplet (SB1) for å forklare minnelekasjer?
- [ ] Lage collection-hjelpere som `cart.addItem` og `cartItem.connectTo`. Metoder som for eksempel inkluderer `.create` og som viser intensjonen bedre.
- [x] `this.model` vs `this.user` etc. Er `this.model` en god default? Hva er dårlige Backbone conventions?
- [x] Backbone = "good practices in a set of reasonably small components"-ish type forklaring. Ikke et rammeverk, men et bibliotek.
- [x] Hvorfor Backbone? Stort community, lightweight, enkelt å integrere i eksisterende kodebase
- [ ] Views må kunne rendres X ganger med samme resultat == idempotent views
- [ ] Promises over eventer når eventene er "svært lokale", for eksempel internt i et view
- [x] Hvem bruker BB? Disqus, Trello, SB1, ... Finn forskjellige typer app-er.
- [x] `MV*`?
- [x] Hva er Backbone i forhold til andre bibliotek/rammeverk. Ikke slå ned på andre, prøve å informere om forskjellen.

**Comment by kimjoar** [comment]
Gjerne legg til nye punkter / strukturer punktene :)

**Comment by hinderberg** [comment]
Siste punkt bør egentlig snakke om hva backbone ikke er. Det er ikke ett komplett rammeverk ut av boksen, men mer ett startpunkt som man kan bygge videre på. Kommer til å fikse på dette i helga!:)

**Comment by hinderberg** [comment]
Hvorfor Backbone? Stort community, lightweight, enkelt å integrere i eksisterende kodebase

Mener at dette ikke er en del av målet med presentasjonen. Men kan være allright å nevne at det er enkelt å integrere i eksisterende kodebase. 

Krysser av når vi har begynt på det i presentasjonen.

**Comment by hinderberg** [comment]
- [ ] få figurene inn i slides
- [ ] fikse på design av slides (make em fancy)
- [ ] Fikse todo oversettelser

**Comment by hinderberg** [comment]
Hehe! :) Så bra @kjbekkelund ;)

**Comment by kimjoar** [comment]
Haha 🙈 Jeg rensket opp i åpne issues jeg hadde på github
